run_only = 1;
_tick = 0;
_animation_idx = 0;
 var _string = "sW" + string(global._wave) + "Crate";
_spriteref = asset_get_index(_string);
_total_idx = sprite_get_number(_spriteref);
_size = 1;
part_emitter_region(global.p_system, global.WhitePartEmitter, x, x, y, y, ps_shape_rectangle, ps_distr_linear);
part_emitter_burst(global.p_system, global.WhitePartEmitter, global.WhitePartType, 45);
part_emitter_region(global.p_system, global.GlintPartEmitter, x, x, y, y, ps_shape_rectangle, ps_distr_linear);
part_emitter_burst(global.p_system, global.GlintPartEmitter, global.GlintPartType, 45);
audio_sound_pitch(snWinAcquire2, pitchscale);
audio_play_sound(snWinAcquire2, 0, false);