name: deploy to surge


on:
  push:
    branches:
      - unstable


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge . https://slugger-snapshot.surge.sh --token ${{ secrets.SURGE_TOKEN }} --yes

      - name: Wait for Surge to finish deployment
        run: sleep 10

      - name: Check if the site is live
        run: |
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null https://slugger-snapshot.surge.sh)
          echo "Response code: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Site is down or unreachable. Status code: $RESPONSE"
            curl -v https://slugger-snapshot.surge.sh  # Verbose mode for detailed info
            exit 1
          else
            echo "Site is live! Status code: $RESPONSE"
          fi
