name: Deploy to GitHub Pages

on:
  push:
    branches:
      - unstable  # Adjust if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy the contents of the `public` folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./SNAPSHOT150-24.46a5exp_surge_package  # Path to the folder with HTML, CSS, and JS files
