name: Deploy to Surge

on:
  push:
    branches:
      - unstable  # Change this if you are using a different branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Surge CLI
        run: npm install --global surge  # Ensure Surge is installed in the Action environment

      - name: Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # We'll set this in the next step
        run: surge . ${{ secrets.SURGE_DOMAIN }} --token $SURGE_TOKEN --yes

      - name: Check if the site is live
        run: |
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null <your-domain>.surge.sh)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Site is down! Status code: $RESPONSE"
            exit 1
          else
            echo "Site is live! Status code: $RESPONSE"
          fi